# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeOU
email: rethore@weou.org
description: A P2P Blockchain Energy Market Solution
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weou.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: weou
github_username:  WeOU
#facebook_username: weou
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/company/17983505

# Address information
address_street: Toppen 227
address_city: Roskilde
#address_state:
address_zip: 4000
address_country: Denmark

# Build settings
markdown: kramdown
